# Generated by Django 6.0.4 on 2026-05-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Responsable', 'Responsable')], default='User', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Utilisateur')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_profil',
                'verbose_name_plural': 'User_profils',
            },
        ),
    ]
