# Generated by Django 6.0.4 on 2026-06-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profil',
            old_name='user_id',
            new_name='user',
        ),
    ]
