# Generated by Django 6.0.4 on 2026-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_user_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Responsable', 'Responsable')], default='User', max_length=50),
        ),
    ]
