# Generated by Django 6.0.4 on 2026-05-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_personne', models.IntegerField()),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=9)),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Non disponible', 'Non disponible')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='equipement/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='hotel/')),
                ('photo', models.ImageField(blank=True, upload_to='hotel/')),
            ],
        ),
        migrations.CreateModel(
            name='Type_chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chambre_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='chambre/')),
                ('chambre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.chambre')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='hote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_pers', models.IntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('Confirmé', 'Confirmé'), ('En attente de validation', 'En attente de validation'), ('Validé', 'Validé')], default='En attente de validation', max_length=50)),
                ('chambre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.chambre')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=50)),
                ('capture', models.ImageField(blank=True, upload_to='payement')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Payé', 'Payé'), ('Non payé', 'Non payé')], default='Non payé', max_length=50)),
                ('mode_payement', models.CharField(choices=[('Sur place', 'Sur place'), ('En ligne', 'En ligne')], default='Sur place', max_length=50)),
                ('reservation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='type_chambre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.type_chambre'),
        ),
    ]
