# Generated by Django 6.0.4 on 2026-05-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='prix_heure',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='prix_jour',
        ),
    ]
