# Generated by Django 6.0.4 on 2026-05-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_prix_heure_chambre_prix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='hote_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='type_chambre_id',
            new_name='type_chambre',
        ),
        migrations.RenameField(
            model_name='payement',
            old_name='reservation_id',
            new_name='reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='chambre_id',
            new_name='chambre',
        ),
        migrations.RemoveField(
            model_name='chambre_photo',
            name='chambre_id',
        ),
        migrations.AddField(
            model_name='chambre_photo',
            name='chambre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel.chambre'),
            preserve_default=False,
        ),
    ]
