# Generated by Django 6.0.4 on 2026-05-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_hote_id_chambre_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='titre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
