# Generated by Django 6.0.4 on 2026-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_chambre_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='mode_payement',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Mobile', 'Mobile')], default='Sur place', max_length=50),
        ),
    ]
