# Generated by Django 6.0.4 on 2026-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_payement_mode_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='hotel.equipement'),
        ),
    ]
