# Generated by Django 6.0.4 on 2026-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_chambre_equipements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='equipements',
            field=models.ManyToManyField(blank=True, related_name='chambres', to='hotel.equipement'),
        ),
    ]
