# Generated by Django 6.0.4 on 2026-06-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_chambre_equipements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Refusé', 'Refusé'), ('En attente de validation', 'En attente de validation'), ('Validé', 'Validé')], default='En attente de validation', max_length=50),
        ),
    ]
