# Generated by Django 6.0.4 on 2026-06-12 04:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_arrivee',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_depart',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
