# Generated by Django 6.0.4 on 2026-06-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
