# Generated by Django 6.0.4 on 2026-06-18 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_contactmessage_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
